name: base_href_rewriter
version: 0.0.0
description: Rewrites Base Href tag in HTML-files.
author: Tais P. Hansen <tais.hansen@gmail.com>
homepage: https://github.com/taisph/base-href-rewriter
environment:
  sdk: '>=1.23.0 <2.0.0'
dependencies:
  barback: ^0.15.2+10
