# Copyright (c) 2017 Tais P. Hansen. All rights reserved.
# This Source Code Form is subject to the terms of the BSD 2-Clause license.
# If a copy of the BSD license was not distributed with this file, you can
# obtain one at http://opensource.org/licenses/BSD-2-Clause.

name: base_href_rewriter
version: 1.0.0-rc.1
description: Rewrites Base Href tag in HTML-files.
author: Tais P. Hansen <tais.hansen@gmail.com>
homepage: https://github.com/taisph/base-href-rewriter
environment:
  sdk: '>=1.23.0 <2.0.0'
dependencies:
  barback: ^0.15.2+10
  html: any
